server:
  servlet:
    context-path: /admin
  port: 80

#filepath: D:/file/

mybatis:
  mapper-locations: classpath:com/dzc/admin/mapper/**/*.xml
  type-aliases-package: com.dzc.admin.model

# 应用名称
spring:
  # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源名称
    name: javaMysql
    # 数据库连接地址
#    url: jdbc:mysql://121.4.252.231:3306/admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://121.4.252.231:3306/admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    # 数据库用户名&密码：
    username: root
    password: dzc021258
    dbcp2:
      min-idle: 5         #数据库连接池的最小维持连接数
      initial-size: 5     #初始化提供的连接数
      max-total: 5          #最大的连接数
      max-wait-millis: 200        #等待连接获取的最大超时时间
  redis:
    port: 6381
    host: 121.4.252.231
    password: dzc123
    database: 0
logging:
  level:
    com:
      dzc:
        admin:
          mapper: debug

  #热部署
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录
      #        additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**
